// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;

import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class GoogleExemplo02Test {
  
  private WebDriver driver;
  private Map<String, Object> vars;
  private String driverPath = "/home/abraao/Downloads/bti/teste2/drivers/chromedriver";
  
  
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", driverPath);
	driver = new ChromeDriver();
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void testeGoogleExemplo02() {
	  driver.get("https://lattes.cnpq.br/");
	  
	  System.out.println("1");
	  WebDriverWait wait = new WebDriverWait(driver, 3);
	  WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.id(".skip-to-content")));
//	  new WebDriverWait(driver, 10).until(
//		      webDriver -> ((JavascriptExecutor) webDriver).executeScript("return document.readyState").equals("complete"));
    
	  System.out.println("2");
	 // WebElement element = driver.findElement(By.cssSelector(".atualizar_cv"));
	  System.out.println(element.getText());
    //driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    //assertThat(driver.getTitle(), is("testes imd - Pesquisa Google"));
  }
}
